import type { AffixDef } from "./types";

/** Normal craftable affixes, with each line limited to the equipment that can roll it. */
export const AFFIX_DATA: AffixDef[] = [
  { id: "acolyte-1-skeleton-and-increased-skeleton-damage", name: "+1 Skeleton and Increased Skeleton Damage", group: "prefix", slots: ["body"], class: "acolyte" },
  { id: "acolyte-additional-projectile-chance-with-chaos-bolts", name: "Acolyte Additional Projectile Chance with Chaos Bolts", group: "prefix", slots: ["helmet"], class: "acolyte" },
  { id: "acolyte-chance-to-apply-damned-on-hit", name: "Acolyte Chance To Apply Damned On Hit", group: "prefix", slots: ["helmet", "body"], class: "acolyte" },
  { id: "acolyte-chance-to-cast-marrow-shards-when-you-cast-transplant", name: "Acolyte Chance To Cast Marrow Shards When You Cast Transplant", group: "prefix", slots: ["helmet", "body"], class: "acolyte" },
  { id: "acolyte-damage-leeched-as-health-while-transformed", name: "Acolyte Damage Leeched As Health While Transformed", group: "prefix", slots: ["helmet", "body"], class: "acolyte" },
  { id: "acolyte-increased-skeletal-mage-damage", name: "Acolyte Increased Skeletal Mage Damage", group: "prefix", slots: ["helmet", "body"], class: "acolyte" },
  { id: "acolyte-minion-freeze-rate", name: "Acolyte Minion Freeze Rate", group: "prefix", slots: ["helmet", "body"], class: "acolyte" },
  { id: "acolyte-physical-spell-critical-strike-chance", name: "Acolyte Physical Spell Critical Strike Chance", group: "prefix", slots: ["helmet", "body"], class: "acolyte" },
  { id: "acolyte-reduced-health-cost-of-spells", name: "Acolyte Reduced Health Cost Of Spells", group: "prefix", slots: ["helmet"], class: "acolyte" },
  { id: "acolyte-spell-damage-per-skeletal-mage", name: "Acolyte Spell Damage Per Skeletal Mage", group: "prefix", slots: ["helmet", "body"], class: "acolyte" },
  { id: "added-health-and-added-health-regeneration", name: "Added Health and Added Health Regeneration", group: "suffix", slots: ["ring", "relic"] },
  { id: "sentinel-added-lightning-throwing-damage-with-javelin", name: "Added Javelin Lightning Throwing Damage", group: "prefix", slots: ["helmet"], class: "sentinel" },
  { id: "added-melee-and-spell-necrotic-damage", name: "Added Melee And Spell Necrotic Damage", group: "prefix", slots: ["one-hand", "two-hand"] },
  { id: "primalist-minion-melee-crit-chance", name: "Added Minion Melee Crit Chance", group: "prefix", slots: ["body"], class: "primalist" },
  { id: "rogue-added-physical-throwing-damage-while-dual-wielding", name: "Added Physical Throwing Damage while Dual Wielding", group: "prefix", slots: ["helmet"], class: "rogue" },
  { id: "all-attributes", name: "All Attributes", group: "suffix", slots: ["two-hand"] },
  { id: "all-res", name: "All Resistances", group: "suffix", slots: ["shield"] },
  { id: "all-resistances-while-channelling", name: "All Resistances while Channelling", group: "suffix", slots: ["relic"] },
  { id: "armor", name: "Armor", group: "suffix", slots: ["helmet", "body", "gloves", "boots", "shield"] },
  { id: "primalist-armor-and-minion-armor", name: "Armor And Minion Armor", group: "prefix", slots: ["helmet", "body"], class: "primalist" },
  { id: "armor-and-reduced-bonus-damage-from-crits", name: "Armor and Reduced Bonus Damage from Crits", group: "suffix", slots: ["helmet", "body", "gloves", "boots", "belt", "shield"] },
  { id: "armor-shred-chance", name: "Armor Shred Chance", group: "suffix", slots: ["gloves", "amulet", "one-hand", "two-hand", "bow", "quiver"] },
  { id: "attunement", name: "Attunement", group: "prefix", slots: ["helmet", "body", "gloves", "boots", "ring", "relic"] },
  { id: "rogue-black-arrows-dropped-by-dark-quiver-and-increased-bow-damage", name: "Black Arrows dropped by Dark Quiver and Increased Bow Damage", group: "prefix", slots: ["body"], class: "rogue" },
  { id: "rogue-bleed-chance-per-equipped-sword", name: "Bleed Chance per Equipped Sword", group: "prefix", slots: ["body"], class: "rogue" },
  { id: "added-block-chance", name: "Block Chance", group: "prefix", slots: ["shield"] },
  { id: "block-chance-and-effectiveness", name: "Block Chance and Effectiveness", group: "suffix", slots: ["gloves", "ring"] },
  { id: "added-block-effectiveness", name: "Block Effectiveness", group: "prefix", slots: ["shield"] },
  { id: "added-bow-cold-damage", name: "Bow Cold Damage", group: "prefix", slots: ["bow", "quiver"] },
  { id: "added-bow-fire-damage", name: "Bow Fire Damage", group: "prefix", slots: ["bow", "quiver"] },
  { id: "added-bow-lightning-damage", name: "Bow Lightning Damage", group: "prefix", slots: ["bow", "quiver"] },
  { id: "added-bow-physical-damage", name: "Bow Physical Damage", group: "prefix", slots: ["bow", "quiver"] },
  { id: "mage-chance-to-apply-frostbite-with-cold-skills", name: "Chance To Apply Frostbite On Hit With Cold Skills", group: "prefix", slots: ["helmet", "body"], class: "mage" },
  { id: "chance-to-blind", name: "Chance To Blind", group: "suffix", slots: ["one-hand", "two-hand", "bow", "quiver"] },
  { id: "mage-chance-to-cast-fire-aura-on-crit", name: "Chance to Cast Fire Aura on Critical Strike (up to 3 times per second)", group: "prefix", slots: ["helmet", "body"], class: "mage" },
  { id: "mage-chance-to-cast-fire-aura-on-kill-with-a-fire-skill", name: "Chance To Cast Fire Aura On Kill Fire Skills (up to 3 times per second)", group: "prefix", slots: ["helmet", "body"], class: "mage" },
  { id: "chance-to-chill", name: "Chance To Chill", group: "suffix", slots: ["one-hand", "two-hand", "bow", "quiver"] },
  { id: "chance-to-chill-attackers", name: "Chance To Chill Attackers", group: "suffix", slots: ["catalyst", "shield"] },
  { id: "primalist-upheaval-shockwave-chance", name: "Chance to create a Shockwave on Hit with Upheaval", group: "prefix", slots: ["body"], class: "primalist" },
  { id: "sentinel-chance-to-electrify-with-lightning-skills", name: "Chance To Electrify with Lightning Skills", group: "prefix", slots: ["helmet", "body"], class: "sentinel" },
  { id: "mage-mana-on-runebolt-or-fireball-cast", name: "Chance to Gain 20 Mana when you directly Cast Runebolt or Fireball", group: "prefix", slots: ["helmet"], class: "mage" },
  { id: "acolyte-chance-to-gain-20-ward-on-kill-with-hungering-souls", name: "Chance to Gain 20 Ward on Kill with Hungering Souls", group: "prefix", slots: ["helmet", "body"], class: "acolyte" },
  { id: "primalist-chance-to-gain-additional-storm-stack", name: "Chance to Gain a Storm Stack when you use Gathering Storm and Hit an enemy", group: "prefix", slots: ["helmet"], class: "primalist" },
  { id: "rogue-crimson-shroud-chance-on-melee-hit", name: "Chance to Gain Crimson Shroud when you use a Melee Attack that Hits", group: "prefix", slots: ["body"], class: "rogue" },
  { id: "rogue-chance-to-gain-dusk-shroud-when-hit", name: "Chance to Gain Dusk Shroud when Hit", group: "prefix", slots: ["body"], class: "rogue" },
  { id: "rogue-dusk-shroud-chance-on-melee-hit", name: "Chance to Gain Dusk Shroud when you use a Melee Attack that Hits", group: "prefix", slots: ["body"], class: "rogue" },
  { id: "mage-chance-to-gain-lightning-aegis-when-hit", name: "Chance to Gain Lightning Aegis when Hit", group: "prefix", slots: ["body"], class: "mage" },
  { id: "chance-to-ignite", name: "Chance To Ignite", group: "suffix", slots: ["amulet", "one-hand", "two-hand", "bow", "quiver"] },
  { id: "mage-chance-to-ignite-with-fire-skills", name: "Chance To Ignite On Hit With Fire Skills", group: "prefix", slots: ["helmet", "body"], class: "mage" },
  { id: "sentinel-chance-to-inflict-bleed-if-wielding-an-axe", name: "Chance to Inflict Bleed if Wielding an Axe", group: "prefix", slots: ["helmet", "body"], class: "sentinel" },
  { id: "rogue-chance-to-inflict-bleed-on-bow-hit", name: "Chance to Inflict Bleed On Bow Hit", group: "prefix", slots: ["helmet", "body"], class: "rogue" },
  { id: "chance-to-inflict-bleed", name: "Chance to Inflict Bleed On Hit", group: "suffix", slots: ["one-hand", "two-hand", "bow", "quiver"] },
  { id: "acolyte-more-damage-over-time-to-bleeding-enemies-for-marrow-shards", name: "Chance to Inflict Bleed On Hit With Marrow Shards", group: "prefix", slots: ["body"], class: "acolyte" },
  { id: "sentinel-chance-to-inflict-time-rot-on-hit-with-void-skills", name: "Chance To Inflict Time Rot on hit with Void Skills", group: "prefix", slots: ["helmet", "body"], class: "sentinel" },
  { id: "chance-to-poison", name: "Chance To Poison", group: "suffix", slots: ["one-hand", "two-hand", "bow", "quiver"] },
  { id: "chance-to-shock", name: "Chance To Shock", group: "suffix", slots: ["amulet", "one-hand", "two-hand", "bow", "quiver"] },
  { id: "chance-to-shock-attackers", name: "Chance To Shock Attackers", group: "suffix", slots: ["catalyst", "shield"] },
  { id: "mage-chance-to-shock-with-lightning-skills", name: "Chance to Shock on Hit with Lightning Skills", group: "prefix", slots: ["helmet", "body"], class: "mage" },
  { id: "chance-to-slow", name: "Chance To Slow", group: "suffix", slots: ["one-hand", "two-hand", "bow", "quiver"] },
  { id: "chance-to-slow-attackers", name: "Chance To Slow Attackers", group: "suffix", slots: ["catalyst", "shield"] },
  { id: "cold-penetration", name: "Cold Penetration", group: "prefix", slots: ["amulet"] },
  { id: "cold-penetration-and-minion-cold-penetration", name: "Cold Penetration and Minion Cold Penetration", group: "suffix", slots: ["one-hand", "two-hand", "bow"] },
  { id: "cold-res", name: "Cold Resistance", group: "suffix", slots: ["helmet", "body", "gloves", "boots", "belt", "ring", "amulet", "relic", "catalyst", "shield", "quiver"] },
  { id: "crit-chance-and-bow-attack-speed", name: "Crit Chance and Bow Attack Speed", group: "prefix", slots: ["bow"] },
  { id: "critical-strike-avoidance-and-added-dodge-rating", name: "Critical Strike Avoidance and Added Dodge Rating", group: "suffix", slots: ["helmet", "gloves", "boots", "belt", "ring"] },
  { id: "acolyte-critical-strike-chance-for-skeletons-and-skeletal-mages", name: "Critical Strike Chance For Skeletons And Skeletal Mages", group: "prefix", slots: ["helmet", "body"], class: "acolyte" },
  { id: "crit-multi", name: "Critical Strike Multiplier", group: "prefix", slots: ["amulet", "relic", "one-hand", "two-hand", "bow", "catalyst"] },
  { id: "rogue-damage-and-area-with-dive-bomb", name: "Damage and Area with Dive Bomb", group: "prefix", slots: ["helmet"], class: "rogue" },
  { id: "damage-dealt-to-mana", name: "Damage Dealt To Mana", group: "prefix", slots: ["helmet", "body"], class: "mage" },
  { id: "increased-minion-damage-over-time", name: "Damage Over Time for Minions", group: "suffix", slots: ["one-hand", "two-hand"] },
  { id: "acolyte-minion-reflect", name: "Damage to Minions Reflected to Attackers", group: "prefix", slots: ["helmet", "body"], class: "acolyte" },
  { id: "damage-while-channelling", name: "Damage while Channelling", group: "prefix", slots: ["amulet", "relic", "two-hand"] },
  { id: "dexterity", name: "Dexterity", group: "prefix", slots: ["helmet", "body", "gloves", "boots", "ring", "relic", "quiver"] },
  { id: "added-dodge-rating", name: "Dodge Rating", group: "suffix", slots: ["helmet", "body", "gloves", "boots", "belt", "ring", "amulet", "catalyst"] },
  { id: "rogue-dodge-rating-if-hit-recently", name: "Dodge Rating if Hit Recently", group: "prefix", slots: ["helmet", "body"], class: "rogue" },
  { id: "dodge-while-evading-and-increased-dodge-rating", name: "Dodge while Evading and Increased Dodge Rating", group: "suffix", slots: ["boots"] },
  { id: "elemental-resistance", name: "Elemental Resistance", group: "suffix", slots: ["helmet", "body", "gloves", "boots", "belt", "ring", "amulet", "relic", "catalyst", "shield", "quiver"] },
  { id: "endurance", name: "Endurance", group: "suffix", slots: ["helmet", "gloves", "belt", "ring", "relic", "shield"] },
  { id: "endurance-threshold", name: "Endurance Threshold", group: "suffix", slots: ["belt"] },
  { id: "sentinel-endurance-while-warpathing", name: "Endurance while Channelling Warpath", group: "prefix", slots: ["body"], class: "sentinel" },
  { id: "extra-potion-slot-and-potion-health", name: "Extra Potion Slot And Potion Health", group: "prefix", slots: ["belt"] },
  { id: "fire-penetration", name: "Fire Penetration", group: "prefix", slots: ["amulet"] },
  { id: "fire-penetration-and-minion-fire-penetration", name: "Fire Penetration and Minion Fire Penetration", group: "suffix", slots: ["one-hand", "two-hand", "bow"] },
  { id: "fire-res", name: "Fire Resistance", group: "suffix", slots: ["helmet", "body", "gloves", "boots", "belt", "ring", "amulet", "relic", "catalyst", "shield", "quiver"] },
  { id: "mage-fireball-pierce-chance", name: "Fireball Pierce Chance", group: "prefix", slots: ["helmet"], class: "mage" },
  { id: "flame-ward-charge-and-added-ward", name: "Flame Ward Charge and Added Ward", group: "prefix", slots: ["body"], class: "mage" },
  { id: "frailty-chance", name: "Frailty Chance", group: "suffix", slots: ["gloves", "amulet", "relic"] },
  { id: "freeze-rate-and-freezing-concoction-on-potion-use", name: "Freeze Rate and Freezing Concoction on Potion Use", group: "prefix", slots: ["belt"] },
  { id: "freeze-rate-multiplier", name: "Freeze Rate Multiplier", group: "suffix", slots: ["one-hand", "two-hand", "catalyst"] },
  { id: "freeze-rate-multiplier-and-cold-resistance", name: "Freeze Rate Multiplier and Cold Resistance", group: "prefix", slots: ["gloves", "ring", "amulet", "relic"] },
  { id: "freeze-rate-per-stack-of-chill", name: "Freeze Rate Per Stack of Chill", group: "prefix", slots: ["helmet", "body"] },
  { id: "mage-frost-wall-duration-and-frostbite-chance", name: "Frost Wall Duration and Frostbite Chance", group: "prefix", slots: ["helmet", "body"], class: "mage" },
  { id: "acolyte-leech-with-harvest", name: "Harvest Damage Leeched as Health", group: "prefix", slots: ["helmet", "body"], class: "acolyte" },
  { id: "health", name: "Health", group: "suffix", slots: ["helmet", "body", "gloves", "boots", "belt", "ring", "amulet", "relic", "shield"] },
  { id: "health-and-stun-avoidance", name: "Health and Stun Avoidance", group: "suffix", slots: ["belt", "amulet"] },
  { id: "health-gained-on-block", name: "Health Gained on Block", group: "prefix", slots: ["shield"] },
  { id: "rogue-health-gained-on-glancing-blow", name: "Health Gained on Glancing Blow", group: "prefix", slots: ["helmet", "body"], class: "rogue" },
  { id: "health-on-kill", name: "Health On Kill", group: "suffix", slots: ["one-hand", "two-hand", "bow", "quiver"] },
  { id: "health-on-melee-hit", name: "Health On Melee Hit", group: "suffix", slots: ["one-hand", "two-hand"] },
  { id: "health-regen", name: "Health Regen per Second", group: "suffix", slots: ["helmet", "gloves", "amulet"] },
  { id: "increased-health-regen", name: "Health Regeneration", group: "suffix", slots: ["helmet", "body", "belt", "ring", "relic"] },
  { id: "hybrid-health", name: "Hybrid Health", group: "suffix", slots: ["gloves", "boots", "belt"] },
  { id: "sentinel-increased-abyssal-decay-duration", name: "Increased Abyssal Decay Duration", group: "prefix", slots: ["helmet", "body"], class: "sentinel" },
  { id: "increased-area-for-area-skills", name: "Increased Area for Area Skills", group: "prefix", slots: ["gloves", "amulet"] },
  { id: "area-for-melee-area-skills", name: "Increased Area for Melee Area Skills", group: "suffix", slots: ["two-hand"] },
  { id: "rogue-increased-acid-flask-area", name: "Increased Area with Acid Flask", group: "prefix", slots: ["helmet", "body"], class: "rogue" },
  { id: "rogue-increased-area-with-cinder-strikes-first-strike", name: "Increased Area with Cinder Strike's First Strike", group: "prefix", slots: ["helmet"], class: "rogue" },
  { id: "increased-armor", name: "Increased Armor", group: "suffix", slots: ["helmet", "body", "boots", "shield"] },
  { id: "rogue-increased-armor-shred-duration", name: "Increased Armor Shred Duration", group: "prefix", slots: ["helmet"], class: "rogue" },
  { id: "increased-bow-attack-speed", name: "Increased Bow Attack Speed", group: "prefix", slots: ["bow", "quiver"] },
  { id: "increased-bow-damage", name: "Increased Bow Damage", group: "prefix", slots: ["bow", "quiver"] },
  { id: "increased-cast-speed", name: "Increased Cast Speed", group: "prefix", slots: ["gloves", "relic", "one-hand", "two-hand", "catalyst"] },
  { id: "increased-chance-to-find-potions", name: "Increased Chance to Find Potions", group: "prefix", slots: ["belt", "amulet"] },
  { id: "increased-cold-damage", name: "Increased Cold Damage", group: "prefix", slots: ["belt", "ring", "amulet", "relic", "one-hand", "two-hand", "bow", "catalyst", "quiver"] },
  { id: "increased-cooldown-recovery-speed", name: "Increased Cooldown Recovery Speed", group: "suffix", slots: ["boots", "belt"] },
  { id: "primalist-cooldown-recovery-speed-while-transformed", name: "Increased Cooldown Recovery Speed while Transformed", group: "prefix", slots: ["helmet"], class: "primalist" },
  { id: "rogue-increased-crit-chance-with-flurry", name: "Increased crit chance with Flurry", group: "prefix", slots: ["helmet", "body"], class: "rogue" },
  { id: "increased-critical-strike-chance", name: "Increased Critical Strike Chance", group: "prefix", slots: ["gloves", "ring", "amulet", "relic", "one-hand", "two-hand", "bow", "catalyst", "quiver"] },
  { id: "acolyte-shared-increased-crit-chance", name: "Increased Critical Strike Chance For You And Your Minions", group: "prefix", slots: ["helmet", "body"], class: "acolyte" },
  { id: "rogue-increased-critical-strike-chance-per-equipped-dagger", name: "Increased Critical Strike Chance per Equipped Dagger", group: "prefix", slots: ["helmet"], class: "rogue" },
  { id: "rogue-increased-critical-strike-chance-per-equipped-sword", name: "Increased Critical Strike Chance per Equipped Sword", group: "prefix", slots: ["body"], class: "rogue" },
  { id: "rogue-increased-damage-of-shadows", name: "Increased Damage of Skills used by Shadows", group: "prefix", slots: ["helmet", "body"], class: "rogue" },
  { id: "increased-damage-over-time", name: "Increased Damage Over Time", group: "prefix", slots: ["gloves", "ring", "amulet", "relic", "one-hand", "two-hand", "bow", "catalyst", "quiver"] },
  { id: "rogue-increased-damage-per-active-shadow-with-shadow-cascade", name: "Increased damage per active Shadow with Shadow Cascade", group: "prefix", slots: ["helmet", "body"], class: "rogue" },
  { id: "acolyte-increased-damage-with-rip-blood-and-blood-splatter", name: "Increased Damage With Rip Blood And Blood Splatter", group: "prefix", slots: ["helmet", "body"], class: "acolyte" },
  { id: "increased-dodge-rating", name: "Increased Dodge Rating", group: "suffix", slots: ["body", "belt", "amulet", "one-hand"] },
  { id: "sentinel-increased-echo-damage-when-a-skill-echoes", name: "Increased Echo Damage When A Skill Echoes", group: "prefix", slots: ["helmet", "body"], class: "sentinel" },
  { id: "increased-elemental-damage", name: "Increased Elemental Damage", group: "prefix", slots: ["ring", "amulet", "one-hand", "two-hand", "catalyst"] },
  { id: "increased-elemental-damage-over-time", name: "Increased Elemental Damage Over Time", group: "prefix", slots: ["belt", "ring", "amulet", "relic", "one-hand", "two-hand"] },
  { id: "increased-fire-damage", name: "Increased Fire Damage", group: "prefix", slots: ["belt", "ring", "amulet", "relic", "one-hand", "two-hand", "bow", "catalyst", "quiver"] },
  { id: "sentinel-increased-fire-damage-and-ignite-duration", name: "Increased Fire Damage And Ignite Duration", group: "prefix", slots: ["helmet", "body"], class: "sentinel" },
  { id: "rogue-increased-hail-of-arrows-duration", name: "Increased Hail of Arrows Duration", group: "prefix", slots: ["helmet"], class: "rogue" },
  { id: "sentinel-increased-hammer-throw-damage", name: "Increased Hammer Throw Damage", group: "prefix", slots: ["helmet", "body"], class: "sentinel" },
  { id: "increased-healing-effectiveness", name: "Increased Healing Effectiveness", group: "prefix", slots: ["ring", "amulet", "relic", "shield"] },
  { id: "increased-health", name: "Increased Health", group: "suffix", slots: ["helmet", "body", "belt"] },
  { id: "increased-lightning-damage", name: "Increased Lightning Damage", group: "prefix", slots: ["belt", "ring", "amulet", "relic", "one-hand", "two-hand", "bow", "catalyst", "quiver"] },
  { id: "increased-mana", name: "Increased Mana", group: "prefix", slots: ["helmet", "body"], class: "rogue" },
  { id: "increased-mana-and-mana-regen", name: "Increased Mana and Mana Regen", group: "prefix", slots: ["helmet", "body"], class: "sentinel" },
  { id: "increased-melee-attack-speed", name: "Increased Melee Attack Speed", group: "prefix", slots: ["gloves", "one-hand", "two-hand"] },
  { id: "increased-melee-damage", name: "Increased Melee Damage", group: "prefix", slots: ["one-hand", "two-hand", "shield"] },
  { id: "increased-minion-damage", name: "Increased Minion Damage", group: "prefix", slots: ["gloves", "belt", "ring", "amulet", "relic", "catalyst", "quiver"] },
  { id: "increased-necrotic-damage", name: "Increased Necrotic Damage", group: "prefix", slots: ["belt", "ring", "amulet", "relic", "one-hand", "two-hand", "catalyst"] },
  { id: "increased-physical-damage", name: "Increased Physical Damage", group: "prefix", slots: ["belt", "ring", "amulet", "relic", "one-hand", "two-hand", "bow", "shield", "quiver"] },
  { id: "sentinel-increased-physical-damage-and-bleed-duration", name: "Increased Physical Damage And Bleed Duration", group: "prefix", slots: ["helmet", "body"], class: "sentinel" },
  { id: "increased-poison-damage", name: "Increased Poison Damage", group: "prefix", slots: ["belt", "ring", "amulet", "relic", "one-hand", "two-hand", "bow", "catalyst", "quiver"] },
  { id: "rogue-increased-poison-duration", name: "Increased Poison Duration", group: "prefix", slots: ["helmet"], class: "rogue" },
  { id: "sentinel-increased-shield-throw-crit-chance", name: "Increased Shield Throw Critical Strike Chance", group: "prefix", slots: ["helmet", "body"], class: "sentinel" },
  { id: "sentinel-increased-smelters-wrath-damage", name: "Increased Smelters Wrath Damage", group: "prefix", slots: ["helmet", "body"], class: "sentinel" },
  { id: "mage-spell-crit-doubled-over-300-max-mana", name: "Increased Spell Crit (Doubled if you have over 300 Max Mana)", group: "prefix", slots: ["helmet", "body"], class: "mage" },
  { id: "increased-spell-crit-chance", name: "Increased Spell Crit Chance", group: "prefix", slots: ["amulet", "relic", "one-hand", "two-hand", "catalyst"] },
  { id: "increased-spell-damage", name: "Increased Spell Damage", group: "prefix", slots: ["ring", "amulet", "one-hand", "two-hand", "catalyst"] },
  { id: "acolyte-increased-spirit-frequency-with-chthonic-fissure", name: "Increased Spirit Frequency with Chthonic Fissure", group: "prefix", slots: ["body"], class: "acolyte" },
  { id: "increased-stun-chance", name: "Increased Stun Chance", group: "suffix", slots: ["gloves", "one-hand", "two-hand", "bow", "quiver"] },
  { id: "increased-melee-stun-chance", name: "Increased Stun Chance with Melee Attacks", group: "suffix", slots: ["one-hand", "two-hand"] },
  { id: "increased-throwing-attack-speed", name: "Increased Throwing Attack Speed", group: "prefix", slots: ["gloves", "ring"] },
  { id: "increased-void-damage", name: "Increased Void Damage", group: "prefix", slots: ["belt", "ring", "amulet", "relic", "one-hand", "two-hand"] },
  { id: "sentinel-increased-void-damage-and-added-spell-void-damage", name: "Increased Void Damage And Added Spell Void Damage", group: "prefix", slots: ["helmet", "body"], class: "sentinel" },
  { id: "intelligence", name: "Intelligence", group: "prefix", slots: ["helmet", "body", "gloves", "boots", "ring", "relic"] },
  { id: "leech-rate", name: "Leech Rate", group: "suffix", slots: ["gloves"] },
  { id: "less-damage-taken-on-block", name: "Less Damage Taken on Block", group: "suffix", slots: ["shield"] },
  { id: "sentinel-level-of-abyssal-echoes", name: "Level of Abyssal Echoes", group: "prefix", slots: ["body"], class: "sentinel" },
  { id: "rogue-level-of-acid-flask", name: "Level of Acid Flask", group: "prefix", slots: ["body"], class: "rogue" },
  { id: "rogue-level-of-aerial-assault", name: "Level of Aerial Assault", group: "prefix", slots: ["relic"], class: "rogue" },
  { id: "sentinel-level-of-anomaly", name: "Level of Anomaly", group: "prefix", slots: ["helmet"], class: "sentinel" },
  { id: "mage-level-of-arcane-ascendance", name: "Level of Arcane Ascendance", group: "prefix", slots: ["body"], class: "mage" },
  { id: "acolyte-level-of-assemble-abomination", name: "Level of Assemble Abomination", group: "prefix", slots: ["relic"], class: "acolyte" },
  { id: "acolyte-level-of-aura-of-decay", name: "Level of Aura Of Decay", group: "prefix", slots: ["relic"], class: "acolyte" },
  { id: "primalist-level-of-avalanche", name: "Level of Avalanche", group: "prefix", slots: ["relic"], class: "primalist" },
  { id: "rogue-level-of-ballista", name: "Level of Ballista", group: "prefix", slots: ["relic"], class: "rogue" },
  { id: "mage-level-of-black-hole", name: "Level of Black Hole", group: "prefix", slots: ["relic"], class: "mage" },
  { id: "rogue-level-of-bladestorm", name: "Level of Bladestorm", group: "prefix", slots: ["helmet"], class: "rogue" },
  { id: "acolyte-level-of-bone-curse", name: "Level of Bone Curse", group: "prefix", slots: ["relic"], class: "acolyte" },
  { id: "acolyte-level-of-chaos-bolts", name: "Level of Chaos Bolts", group: "prefix", slots: ["helmet"], class: "acolyte" },
  { id: "acolyte-level-of-chthonic-fissure", name: "Level of Chthonic Fissure", group: "prefix", slots: ["body"], class: "acolyte" },
  { id: "rogue-level-of-cinder-strike", name: "Level of Cinder Strike", group: "prefix", slots: ["relic"], class: "rogue" },
  { id: "rogue-level-of-dancing-strikes", name: "Level of Dancing Strikes", group: "prefix", slots: ["relic"], class: "rogue" },
  { id: "rogue-level-of-dark-quiver", name: "Level of Dark Quiver", group: "prefix", slots: ["helmet"], class: "rogue" },
  { id: "acolyte-level-of-death-seal", name: "Level of Death Seal", group: "prefix", slots: ["helmet"], class: "acolyte" },
  { id: "rogue-level-of-decoy", name: "Level of Decoy", group: "prefix", slots: ["helmet"], class: "rogue" },
  { id: "rogue-level-of-detonating-arrow", name: "Level of Detonating Arrow", group: "prefix", slots: ["body"], class: "rogue" },
  { id: "sentinel-level-of-devouring-orb", name: "Level of Devouring Orb", group: "prefix", slots: ["helmet"], class: "sentinel" },
  { id: "mage-level-of-disintegrate", name: "Level of Disintegrate", group: "prefix", slots: ["relic"], class: "mage" },
  { id: "rogue-level-of-dive-bomb", name: "Level of Dive Bomb", group: "prefix", slots: ["body"], class: "rogue" },
  { id: "acolyte-level-of-drain-life", name: "Level of Drain Life", group: "prefix", slots: ["body"], class: "acolyte" },
  { id: "acolyte-level-of-dread-shade", name: "Level of Dread Shade", group: "prefix", slots: ["body"], class: "acolyte" },
  { id: "rogue-level-of-dreamslash", name: "Level of Dreamslash", group: "prefix", slots: ["helmet"], class: "rogue" },
  { id: "primalist-level-of-earthquake", name: "Level of Earthquake", group: "prefix", slots: ["helmet"], class: "primalist" },
  { id: "mage-level-of-elemental-nova", name: "Level of Elemental Nova", group: "prefix", slots: ["helmet"], class: "mage" },
  { id: "mage-level-of-enchant-weapon", name: "Level of Enchant Weapon", group: "prefix", slots: ["helmet"], class: "mage" },
  { id: "primalist-level-of-entangling-roots", name: "Level of Entangling Roots", group: "prefix", slots: ["helmet"], class: "primalist" },
  { id: "sentinel-level-of-erasing-strike", name: "Level of Erasing Strike", group: "prefix", slots: ["body"], class: "sentinel" },
  { id: "primalist-level-of-eterras-blessing", name: "Level of Eterra's Blessing", group: "prefix", slots: ["body"], class: "primalist" },
  { id: "rogue-level-of-explosive-trap", name: "Level of Explosive Trap", group: "prefix", slots: ["body"], class: "rogue" },
  { id: "rogue-level-of-falconry", name: "Level of Falconry", group: "prefix", slots: ["helmet"], class: "rogue" },
  { id: "mage-level-of-fireball", name: "Level of Fireball", group: "prefix", slots: ["body"], class: "mage" },
  { id: "mage-level-of-firebrand", name: "Level of Firebrand", group: "prefix", slots: ["body"], class: "mage" },
  { id: "mage-level-of-flame-reave", name: "Level of Flame Reave", group: "prefix", slots: ["body"], class: "mage" },
  { id: "mage-level-of-flame-rush", name: "Level of Flame Rush", group: "prefix", slots: ["body"], class: "mage" },
  { id: "mage-level-of-flame-ward", name: "Level of Flame Ward", group: "prefix", slots: ["relic"], class: "mage" },
  { id: "acolyte-level-of-flay", name: "Level of Flay", group: "prefix", slots: ["body"], class: "acolyte" },
  { id: "rogue-level-of-flurry", name: "Level of Flurry", group: "prefix", slots: ["relic"], class: "rogue" },
  { id: "mage-level-of-focus", name: "Level of Focus", group: "prefix", slots: ["helmet"], class: "mage" },
  { id: "sentinel-level-of-forge-strike", name: "Level of Forge Strike", group: "prefix", slots: ["body"], class: "sentinel" },
  { id: "mage-level-of-frost-claw", name: "Level of Frost Claw", group: "prefix", slots: ["relic"], class: "mage" },
  { id: "mage-level-of-frostwall", name: "Level of Frostwall", group: "prefix", slots: ["relic"], class: "mage" },
  { id: "primalist-level-of-fury-leap", name: "Level of Fury Leap", group: "prefix", slots: ["relic"], class: "primalist" },
  { id: "primalist-level-of-gathering-storm", name: "Level of Gathering Storm", group: "prefix", slots: ["body"], class: "primalist" },
  { id: "acolyte-level-of-ghostflame", name: "Level of Ghostflame", group: "prefix", slots: ["helmet"], class: "acolyte" },
  { id: "mage-level-of-glacier", name: "Level of Glacier", group: "prefix", slots: ["body"], class: "mage" },
  { id: "mage-level-of-glyph-of-dominion", name: "Level of Glyph of Dominion", group: "prefix", slots: ["relic"], class: "mage" },
  { id: "rogue-level-of-hail-of-arrows", name: "Level of Hail of Arrows", group: "prefix", slots: ["body"], class: "rogue" },
  { id: "sentinel-level-of-hammer-throw", name: "Level of Hammer Throw", group: "prefix", slots: ["relic"], class: "sentinel" },
  { id: "acolyte-level-of-harvest", name: "Level of Harvest", group: "prefix", slots: ["relic"], class: "acolyte" },
  { id: "sentinel-level-of-healing-hands", name: "Level of Healing Hands", group: "prefix", slots: ["helmet"], class: "sentinel" },
  { id: "rogue-level-of-heartseeker", name: "Level of Heartseeker", group: "prefix", slots: ["body"], class: "rogue" },
  { id: "sentinel-level-of-holy-aura", name: "Level of Holy Aura", group: "prefix", slots: ["relic"], class: "sentinel" },
  { id: "acolyte-level-of-hungering-souls", name: "Level of Hungering Souls", group: "prefix", slots: ["helmet"], class: "acolyte" },
  { id: "mage-level-of-ice-barrage", name: "Level of Ice Barrage", group: "prefix", slots: ["body"], class: "mage" },
  { id: "acolyte-level-of-infernal-shade", name: "Level of Infernal Shade", group: "prefix", slots: ["relic"], class: "acolyte" },
  { id: "sentinel-level-of-javelin", name: "Level of Javelin", group: "prefix", slots: ["relic"], class: "sentinel" },
  { id: "sentinel-level-of-judgement", name: "Level of Judgement", group: "prefix", slots: ["relic"], class: "sentinel" },
  { id: "rogue-level-of-lethal-mirage", name: "Level of Lethal Mirage", group: "prefix", slots: ["relic"], class: "rogue" },
  { id: "mage-level-of-lightning-blast", name: "Level of Lightning Blast", group: "prefix", slots: ["helmet"], class: "mage" },
  { id: "sentinel-level-of-lunge", name: "Level of Lunge", group: "prefix", slots: ["body"], class: "sentinel" },
  { id: "primalist-level-of-maelstrom", name: "Level of Maelstrom", group: "prefix", slots: ["body"], class: "primalist" },
  { id: "mage-level-of-mana-strike", name: "Level of Mana Strike", group: "prefix", slots: ["body"], class: "mage" },
  { id: "sentinel-level-of-manifest-armor", name: "Level of Manifest Armor", group: "prefix", slots: ["helmet"], class: "sentinel" },
  { id: "acolyte-level-of-marrow-shards", name: "Level of Marrow Shards", group: "prefix", slots: ["helmet"], class: "acolyte" },
  { id: "mage-level-of-meteor", name: "Level of Meteor", group: "prefix", slots: ["body"], class: "mage" },
  { id: "rogue-level-of-multishot", name: "Level of Multishot", group: "prefix", slots: ["helmet"], class: "rogue" },
  { id: "sentinel-level-of-multistrike", name: "Level of Multistrike", group: "prefix", slots: ["body"], class: "sentinel" },
  { id: "rogue-level-of-net", name: "Level of Net", group: "prefix", slots: ["relic"], class: "rogue" },
  { id: "acolyte-level-of-profane-veil", name: "Level of Profane Veil", group: "prefix", slots: ["relic"], class: "acolyte" },
  { id: "rogue-level-of-puncture", name: "Level of Puncture", group: "prefix", slots: ["helmet"], class: "rogue" },
  { id: "sentinel-level-of-radiant-lance", name: "Level of Radiant Lance", group: "prefix", slots: ["body"], class: "sentinel" },
  { id: "acolyte-level-of-reaper-form", name: "Level of Reaper Form", group: "prefix", slots: ["body"], class: "acolyte" },
  { id: "sentinel-level-of-rebuke", name: "Level of Rebuke", group: "prefix", slots: ["relic"], class: "sentinel" },
  { id: "sentinel-level-of-ring-of-shields", name: "Level of Ring Of Shields", group: "prefix", slots: ["helmet"], class: "sentinel" },
  { id: "acolyte-level-of-rip-blood", name: "Level of Rip Blood", group: "prefix", slots: ["helmet"], class: "acolyte" },
  { id: "sentinel-level-of-rive", name: "Level of Rive", group: "prefix", slots: ["body"], class: "sentinel" },
  { id: "mage-level-of-runebolt", name: "Level of Runebolt", group: "prefix", slots: ["helmet"], class: "mage" },
  { id: "mage-level-of-runic-invocation", name: "Level of Runic Invocation", group: "prefix", slots: ["helmet"], class: "mage" },
  { id: "acolyte-level-of-sacrifice", name: "Level of Sacrifice", group: "prefix", slots: ["body"], class: "acolyte" },
  { id: "primalist-level-of-serpent-strike", name: "Level of Serpent Strike", group: "prefix", slots: ["relic"], class: "primalist" },
  { id: "rogue-level-of-shadow-cascade", name: "Level of Shadow Cascade", group: "prefix", slots: ["body"], class: "rogue" },
  { id: "rogue-level-of-shadow-rend", name: "Level of Shadow Rend", group: "prefix", slots: ["relic"], class: "rogue" },
  { id: "mage-level-of-shatter-strike", name: "Level of Shatter Strike", group: "prefix", slots: ["body"], class: "mage" },
  { id: "sentinel-level-of-shield-bash", name: "Level of Shield Bash", group: "prefix", slots: ["relic"], class: "sentinel" },
  { id: "sentinel-level-of-shield-rush", name: "Level of Shield Rush", group: "prefix", slots: ["body"], class: "sentinel" },
  { id: "sentinel-level-of-shield-throw", name: "Level of Shield Throw", group: "prefix", slots: ["helmet"], class: "sentinel" },
  { id: "rogue-level-of-shift", name: "Level of Shift", group: "prefix", slots: ["body"], class: "rogue" },
  { id: "rogue-level-of-shurikens", name: "Level of Shurikens", group: "prefix", slots: ["helmet"], class: "rogue" },
  { id: "sentinel-level-of-smelters-wrath", name: "Level of Smelter's Wrath", group: "prefix", slots: ["helmet"], class: "sentinel" },
  { id: "sentinel-level-of-smite", name: "Level of Smite", group: "prefix", slots: ["relic"], class: "sentinel" },
  { id: "rogue-level-of-smoke-bomb", name: "Level of Smoke Bomb", group: "prefix", slots: ["body"], class: "rogue" },
  { id: "mage-level-of-snap-freeze", name: "Level of Snap Freeze", group: "prefix", slots: ["relic"], class: "mage" },
  { id: "acolyte-level-of-soul-feast", name: "Level of Soul Feast", group: "prefix", slots: ["body"], class: "acolyte" },
  { id: "acolyte-level-of-spirit-plague", name: "Level of Spirit Plague", group: "prefix", slots: ["helmet"], class: "acolyte" },
  { id: "primalist-level-of-spriggan-form", name: "Level of Spriggan Form", group: "prefix", slots: ["relic"], class: "primalist" },
  { id: "mage-level-of-static", name: "Level of Static", group: "prefix", slots: ["relic"], class: "mage" },
  { id: "mage-level-of-static-orb", name: "Level of Static Orb", group: "prefix", slots: ["helmet"], class: "mage" },
  { id: "primalist-level-of-summon-bear", name: "Level of Summon Bear", group: "prefix", slots: ["helmet"], class: "primalist" },
  { id: "acolyte-level-of-summon-bone-golem", name: "Level of Summon Bone Golem", group: "prefix", slots: ["helmet"], class: "acolyte" },
  { id: "primalist-level-of-summon-frenzy-totem", name: "Level of Summon Frenzy Totem", group: "prefix", slots: ["relic"], class: "primalist" },
  { id: "primalist-level-of-summon-raptor", name: "Level of Summon Raptor", group: "prefix", slots: ["body"], class: "primalist" },
  { id: "primalist-level-of-summon-sabertooth", name: "Level of Summon Sabertooth", group: "prefix", slots: ["relic"], class: "primalist" },
  { id: "primalist-level-of-summon-scorpion", name: "Level of Summon Scorpion", group: "prefix", slots: ["relic"], class: "primalist" },
  { id: "acolyte-level-of-summon-skeletal-mage", name: "Level of Summon Skeletal Mage", group: "prefix", slots: ["relic"], class: "acolyte" },
  { id: "acolyte-level-of-summon-skeleton", name: "Level of Summon Skeleton", group: "prefix", slots: ["body"], class: "acolyte" },
  { id: "primalist-level-of-summon-spriggan", name: "Level of Summon Spriggan", group: "prefix", slots: ["helmet"], class: "primalist" },
  { id: "primalist-level-of-summon-storm-crow", name: "Level of Summon Storm Crow", group: "prefix", slots: ["body"], class: "primalist" },
  { id: "primalist-level-of-summon-storm-totem", name: "Level of Summon Storm Totem", group: "prefix", slots: ["helmet"], class: "primalist" },
  { id: "primalist-level-of-summon-thorn-totem", name: "Level of Summon Thorn Totem", group: "prefix", slots: ["helmet"], class: "primalist" },
  { id: "primalist-level-of-summon-tide-elemental", name: "Level of Summon Tide Elemental", group: "prefix", slots: ["relic"], class: "primalist" },
  { id: "acolyte-level-of-summon-volatile-zombie", name: "Level of Summon Volatile Zombie", group: "prefix", slots: ["helmet"], class: "acolyte" },
  { id: "primalist-level-of-summon-wolf", name: "Level of Summon Wolf", group: "prefix", slots: ["helmet"], class: "primalist" },
  { id: "acolyte-level-of-summon-wraith", name: "Level of Summon Wraith", group: "prefix", slots: ["body"], class: "acolyte" },
  { id: "mage-level-of-surge", name: "Level of Surge", group: "prefix", slots: ["relic"], class: "mage" },
  { id: "primalist-level-of-swarmblade-form", name: "Level of Swarmblade Form", group: "prefix", slots: ["body"], class: "primalist" },
  { id: "primalist-level-of-swipe", name: "Level of Swipe", group: "prefix", slots: ["relic"], class: "primalist" },
  { id: "sentinel-level-of-symbols-of-hope", name: "Level of Symbols Of Hope", group: "prefix", slots: ["relic"], class: "sentinel" },
  { id: "rogue-level-of-synchronized-strike", name: "Level of Synchronized Strike", group: "prefix", slots: ["helmet"], class: "rogue" },
  { id: "mage-level-of-teleport", name: "Level of Teleport", group: "prefix", slots: ["helmet"], class: "mage" },
  { id: "primalist-level-of-tempest-strike", name: "Level of Tempest Strike", group: "prefix", slots: ["body"], class: "primalist" },
  { id: "primalist-level-of-tornado", name: "Level of Tornado", group: "prefix", slots: ["body"], class: "primalist" },
  { id: "acolyte-level-of-transplant", name: "Level of Transplant", group: "prefix", slots: ["relic"], class: "acolyte" },
  { id: "rogue-level-of-umbral-blades", name: "Level of Umbral Blades", group: "prefix", slots: ["relic"], class: "rogue" },
  { id: "primalist-level-of-upheaval", name: "Level of Upheaval", group: "prefix", slots: ["body"], class: "primalist" },
  { id: "sentinel-level-of-vengeance", name: "Level of Vengeance", group: "prefix", slots: ["helmet"], class: "sentinel" },
  { id: "sentinel-level-of-void-cleave", name: "Level of Void Cleave", group: "prefix", slots: ["relic"], class: "sentinel" },
  { id: "sentinel-level-of-volatile-reversal", name: "Level of Volatile Reversal", group: "prefix", slots: ["helmet"], class: "sentinel" },
  { id: "mage-level-of-volcanic-orb", name: "Level of Volcanic Orb", group: "prefix", slots: ["relic"], class: "mage" },
  { id: "acolyte-level-of-wandering-spirits", name: "Level of Wandering Spirits", group: "prefix", slots: ["body"], class: "acolyte" },
  { id: "primalist-level-of-warcry", name: "Level of Warcry", group: "prefix", slots: ["relic"], class: "primalist" },
  { id: "sentinel-level-of-warpath", name: "Level of Warpath", group: "prefix", slots: ["body"], class: "sentinel" },
  { id: "primalist-level-of-werebear-form", name: "Level of Werebear Form", group: "prefix", slots: ["helmet"], class: "primalist" },
  { id: "lightning-damage-and-leech", name: "Lightning Damage And Leech", group: "prefix", slots: ["one-hand"] },
  { id: "rogue-lightning-damage-with-shurikens", name: "Lightning Damage with Shurikens", group: "prefix", slots: ["helmet", "body"], class: "rogue" },
  { id: "lightning-penetration", name: "Lightning Penetration", group: "prefix", slots: ["amulet"] },
  { id: "lightning-penetration-and-minion-lightning-penetration", name: "Lightning Penetration and Minion Lightning Penetration", group: "suffix", slots: ["one-hand", "two-hand", "bow"] },
  { id: "lightning-res", name: "Lightning Resistance", group: "suffix", slots: ["helmet", "body", "gloves", "boots", "belt", "ring", "amulet", "relic", "catalyst", "shield", "quiver"] },
  { id: "mage-chance-to-apply-a-spark-charge-on-melee-hit", name: "Mage Chance to Apply a Spark Charge on Melee Hit", group: "prefix", slots: ["helmet"], class: "mage" },
  { id: "mage-chance-to-cast-fire-aura-when-hit", name: "Mage Chance To Cast Fire Aura When Hit", group: "prefix", slots: ["helmet", "body"], class: "mage" },
  { id: "mage-cold-penetration-with-frostbite", name: "Mage Cold Penetration With Frostbite", group: "prefix", slots: ["helmet", "body"], class: "mage" },
  { id: "mage-flame-rush-speed", name: "Mage Flame Rush Speed", group: "prefix", slots: ["helmet"], class: "mage" },
  { id: "mage-increased-cold-damage-over-time", name: "Mage Increased Cold Damage Over Time", group: "prefix", slots: ["helmet", "body"], class: "mage" },
  { id: "mage-increased-fire-aura-damage", name: "Mage Increased Fire Aura Damage", group: "prefix", slots: ["helmet", "body"], class: "mage" },
  { id: "mage-increased-fire-damage-over-time", name: "Mage Increased Fire Damage Over Time", group: "prefix", slots: ["helmet", "body"], class: "mage" },
  { id: "mage-increased-melee-elemental-damage", name: "Mage Increased Melee Elemental Damage", group: "prefix", slots: ["helmet", "body"], class: "mage" },
  { id: "mage-lightning-crit-multi", name: "Mage Lightning Crit Multi", group: "prefix", slots: ["helmet", "body"], class: "mage" },
  { id: "mage-mana-spent-gained-as-ward", name: "Mage Mana Spent Gained as Ward", group: "prefix", slots: ["helmet", "body"], class: "mage" },
  { id: "mage-ward-per-second-on-glyph-of-dominion", name: "Mage Ward per Second on Glyph of Dominion", group: "prefix", slots: ["body"], class: "mage" },
  { id: "added-mana", name: "Mana", group: "prefix", slots: ["helmet", "body", "gloves", "amulet", "relic", "catalyst"] },
  { id: "mana-and-mana-regen", name: "Mana and Mana Regen", group: "prefix", slots: ["one-hand", "two-hand"] },
  { id: "mana-and-mana-spent-gained-as-ward", name: "Mana and Mana Spent Gained as Ward", group: "prefix", slots: ["one-hand", "two-hand"] },
  { id: "rogue-mana-efficiency-with-decoy", name: "Mana efficiency with Decoy", group: "prefix", slots: ["helmet", "body"], class: "rogue" },
  { id: "rogue-mana-efficiency-with-synchronised-strike", name: "Mana efficiency with Synchronised Strike", group: "prefix", slots: ["helmet", "body"], class: "rogue" },
  { id: "acolyte-mana-gained-on-harvest-use", name: "Mana Gained on Harvest Use", group: "prefix", slots: ["body"], class: "acolyte" },
  { id: "sentinel-mana-gained-on-smite-use", name: "Mana Gained when you directly Cast Smite", group: "prefix", slots: ["helmet"], class: "sentinel" },
  { id: "sentinel-mana-gained-on-rive-hit", name: "Mana Gained when you use Rive and Hit at least one enemy", group: "prefix", slots: ["helmet"], class: "sentinel" },
  { id: "sentinel-mana-gained-on-vengeance-hit", name: "Mana Gained when you use Vengeance and Hit at least one enemy", group: "prefix", slots: ["body"], class: "sentinel" },
  { id: "increased-mana-regen", name: "Mana Regeneration", group: "prefix", slots: ["belt", "ring", "amulet", "relic"] },
  { id: "rogue-max-ballista-and-increased-ballista-attack-speed", name: "Max Ballista and Increased Ballista Attack Speed", group: "prefix", slots: ["body"], class: "rogue" },
  { id: "added-melee-cold-damage", name: "Melee Cold Damage", group: "prefix", slots: ["one-hand", "two-hand"] },
  { id: "added-melee-crit-chance", name: "Melee Crit Chance", group: "prefix", slots: ["one-hand", "two-hand"] },
  { id: "melee-fire-damage", name: "Melee Fire Damage", group: "prefix", slots: ["one-hand", "two-hand"] },
  { id: "melee-frailty-chance", name: "Melee Frailty Chance", group: "suffix", slots: ["one-hand", "two-hand"] },
  { id: "melee-health-leech", name: "Melee Health Leech", group: "prefix", slots: ["gloves", "one-hand", "two-hand"] },
  { id: "added-melee-lightning-damage", name: "Melee Lightning Damage", group: "prefix", slots: ["one-hand", "two-hand"] },
  { id: "added-melee-physical-damage", name: "Melee Physical Damage", group: "prefix", slots: ["one-hand", "two-hand"] },
  { id: "added-melee-void-damage", name: "Melee Void Damage", group: "prefix", slots: ["one-hand", "two-hand"] },
  { id: "minion-area-and-damage", name: "Minion Area and Damage", group: "prefix", slots: ["gloves", "amulet"] },
  { id: "primalist-minion-chance-to-inflict-bleed-on-hit", name: "Minion Chance to Inflict Bleed on Hit", group: "prefix", slots: ["helmet", "body"], class: "primalist" },
  { id: "minion-dodge-rating", name: "Minion Dodge Rating", group: "prefix", slots: ["helmet", "boots", "ring", "relic"] },
  { id: "minion-health", name: "Minion Health", group: "prefix", slots: ["helmet", "body", "gloves", "belt", "ring", "amulet", "relic", "catalyst", "shield"] },
  { id: "minion-health-regen", name: "Minion Health Regen", group: "prefix", slots: ["helmet", "belt", "relic"] },
  { id: "minion-melee-and-bow-damage", name: "Minion Melee and Bow Damage", group: "suffix", slots: ["one-hand", "two-hand", "bow"] },
  { id: "minion-melee-spell-damage", name: "Minion Melee and Spell Damage", group: "suffix", slots: ["one-hand", "two-hand"] },
  { id: "primalist-minion-melee-leech", name: "Minion Melee Damage Leeched As Health", group: "prefix", slots: ["helmet", "body"], class: "primalist" },
  { id: "minion-spell-and-bow-damage", name: "Minion Spell and Bow Damage", group: "suffix", slots: ["one-hand", "two-hand"] },
  { id: "rogue-mirages-and-mana-efficiency-with-lethal-mirage", name: "Mirages and Mana Efficiency with Lethal Mirage", group: "prefix", slots: ["body"], class: "rogue" },
  { id: "movement-speed", name: "Movement Speed", group: "prefix", slots: ["boots"] },
  { id: "acolyte-necrotic-damage-while-transformed", name: "Necrotic Damage while Transformed", group: "prefix", slots: ["helmet", "body"], class: "acolyte" },
  { id: "necrotic-penetration", name: "Necrotic Penetration", group: "prefix", slots: ["amulet"] },
  { id: "necrotic-penetration-and-minion-necrotic-penetration", name: "Necrotic Penetration and Minion Necrotic Penetration", group: "suffix", slots: ["one-hand", "two-hand"] },
  { id: "necrotic-res", name: "Necrotic Resistance", group: "suffix", slots: ["helmet", "body", "gloves", "boots", "belt", "ring", "amulet", "relic", "catalyst", "shield", "quiver"] },
  { id: "parry-chance", name: "Parry Chance", group: "prefix", slots: ["one-hand", "two-hand"] },
  { id: "mage-penetration-with-cold-invocations", name: "Penetration with Cold Invocations", group: "prefix", slots: ["helmet", "body"], class: "mage" },
  { id: "mage-penetration-with-fire-invocations", name: "Penetration with Fire Invocations", group: "prefix", slots: ["helmet", "body"], class: "mage" },
  { id: "mage-penetration-with-lightning-invocations", name: "Penetration with Lightning Invocations", group: "prefix", slots: ["helmet", "body"], class: "mage" },
  { id: "percent-damage-reflected", name: "Percent Damage Reflected", group: "prefix", slots: ["body", "shield"] },
  { id: "acolyte-physical-damage-while-transformed", name: "Physical Damage while Transformed", group: "prefix", slots: ["helmet", "body"], class: "acolyte" },
  { id: "physical-penetration", name: "Physical Penetration", group: "prefix", slots: ["amulet"] },
  { id: "physical-penetration-and-minion-physical-penetration", name: "Physical Penetration and Minion Physical Penetration", group: "suffix", slots: ["one-hand", "two-hand", "bow"] },
  { id: "physical-res", name: "Physical Resistance", group: "suffix", slots: ["helmet", "body", "gloves", "boots", "belt", "ring", "amulet", "relic", "shield", "quiver"] },
  { id: "rogue-poison-chance-per-equipped-dagger", name: "Poison Chance per Equipped Dagger", group: "prefix", slots: ["helmet"], class: "rogue" },
  { id: "acolyte-poison-damage-and-poison-resistance", name: "Poison Damage And Poison Resistance", group: "prefix", slots: ["helmet", "body"], class: "acolyte" },
  { id: "poison-penetration", name: "Poison Penetration", group: "prefix", slots: ["amulet"] },
  { id: "poison-penetration-and-minion-poison-penetration", name: "Poison Penetration and Minion Poison Penetration", group: "suffix", slots: ["one-hand", "two-hand", "bow"] },
  { id: "poison-res", name: "Poison Resistance", group: "suffix", slots: ["helmet", "body", "gloves", "boots", "belt", "ring", "amulet", "relic", "catalyst", "shield", "quiver"] },
  { id: "potion-health-converted-to-ward", name: "Potion Health Converted to Ward", group: "prefix", slots: ["gloves", "belt", "ring", "relic"] },
  { id: "primalist-added-spell-damage-with-tempest-strike", name: "Primalist Added Spell Damage With Tempest Strike", group: "prefix", slots: ["helmet"], class: "primalist" },
  { id: "primalist-armor-shred-chance-for-locusts", name: "Primalist Armor Shred Chance for Locusts", group: "prefix", slots: ["body"], class: "primalist" },
  { id: "primalist-attack-and-cast-speed-for-summoned-vines", name: "Primalist Attack and Cast Speed for Summoned Vines", group: "prefix", slots: ["helmet"], class: "primalist" },
  { id: "primalist-criti-multi-while-transformed", name: "Primalist Criti Multi While Transformed", group: "prefix", slots: ["helmet", "body"], class: "primalist" },
  { id: "primalist-critical-strike-chance-with-rampage", name: "Primalist Critical Strike Chance with Rampage", group: "prefix", slots: ["body"], class: "primalist" },
  { id: "primalist-damage-over-time-while-transformed", name: "Primalist Damage Over Time While Transformed", group: "prefix", slots: ["helmet", "body"], class: "primalist" },
  { id: "primalist-increased-aspect-of-the-boar-duration", name: "Primalist Increased Aspect Of The Boar Duration", group: "prefix", slots: ["helmet", "body"], class: "primalist" },
  { id: "primalist-increased-aspect-of-the-lynx-effect", name: "Primalist Increased Aspect Of The Lynx Effect", group: "prefix", slots: ["helmet", "body"], class: "primalist" },
  { id: "primalist-increased-aspect-of-the-shark-effect", name: "Primalist Increased Aspect Of The Shark Effect", group: "prefix", slots: ["helmet", "body"], class: "primalist" },
  { id: "primalist-increased-aspect-of-the-viper-effect", name: "Primalist Increased Aspect Of The Viper Effect", group: "prefix", slots: ["helmet", "body"], class: "primalist" },
  { id: "primalist-melee-damage-while-transformed", name: "Primalist Melee Damage While Transformed", group: "prefix", slots: ["helmet", "body"], class: "primalist" },
  { id: "primalist-minion-crit-multiplier", name: "Primalist Minion Crit Multiplier", group: "prefix", slots: ["helmet", "body"], class: "primalist" },
  { id: "primalist-minion-spell-crit-chance", name: "Primalist Minion Spell Crit Chance", group: "prefix", slots: ["helmet", "body"], class: "primalist" },
  { id: "primalist-spell-damage-while-transformed", name: "Primalist Spell Damage While Transformed", group: "prefix", slots: ["helmet", "body"], class: "primalist" },
  { id: "primalist-storm-crow-added-spell-damage", name: "Primalist Storm Crow Added Spell Damage", group: "prefix", slots: ["helmet"], class: "primalist" },
  { id: "primalist-totem-added-spell-damage", name: "Primalist Totem Added Spell Damage", group: "prefix", slots: ["helmet", "body"], class: "primalist" },
  { id: "primalist-totem-increased-cast-speed", name: "Primalist Totem Increased Cast Speed", group: "prefix", slots: ["helmet", "body"], class: "primalist" },
  { id: "rogue-recurve-chance-with-heartseeker", name: "Recurve Chance", group: "prefix", slots: ["helmet", "body"], class: "rogue" },
  { id: "less-bonus-damage-taken-from-critical-strikes", name: "Reduced Bonus Damage Taken from Critical Strikes", group: "suffix", slots: ["two-hand"] },
  { id: "rogue-armor-shred-effect", name: "Rogue Armor Shred Effect", group: "prefix", slots: ["body"], class: "rogue" },
  { id: "rogue-bleed-chance-with-shurikens", name: "Rogue Bleed Chance with Shurikens", group: "prefix", slots: ["helmet", "body"], class: "rogue" },
  { id: "rogue-chance-to-ignite-on-bow-hit", name: "Rogue Chance to Ignite on Bow Hit", group: "prefix", slots: ["helmet"], class: "rogue" },
  { id: "rogue-chance-to-shred-armor-on-bow-hit", name: "Rogue Chance to Shred Armor on Bow Hit", group: "prefix", slots: ["helmet"], class: "rogue" },
  { id: "rogue-chance-to-shred-armor-on-melee-hit", name: "Rogue Chance to Shred Armor on Melee Hit", group: "prefix", slots: ["body"], class: "rogue" },
  { id: "rogue-chance-to-shred-armor-on-throwing-hit", name: "Rogue Chance to Shred Armor on Throwing Hit", group: "prefix", slots: ["body"], class: "rogue" },
  { id: "rogue-chance-to-slow-on-bow-hit", name: "Rogue Chance to Slow on Bow Hit", group: "prefix", slots: ["helmet"], class: "rogue" },
  { id: "rogue-fire-penetration-with-ignite", name: "Rogue Fire Penetration With Ignite", group: "prefix", slots: ["helmet", "body"], class: "rogue" },
  { id: "rogue-increased-area-with-detonating-arrow", name: "Rogue Increased Area with Detonating Arrow", group: "prefix", slots: ["helmet", "body"], class: "rogue" },
  { id: "rogue-increased-bow-elemental-damage", name: "Rogue Increased Bow Elemental Damage", group: "prefix", slots: ["helmet"], class: "rogue" },
  { id: "rogue-increased-damage-per-arrow-with-multishot", name: "Rogue Increased damage per arrow with Multishot", group: "prefix", slots: ["helmet", "body"], class: "rogue" },
  { id: "rogue-increased-damage-while-wielding-a-bow", name: "Rogue Increased damage while wielding a bow", group: "prefix", slots: ["helmet", "body"], class: "rogue" },
  { id: "rogue-increased-damage-while-wielding-a-dagger", name: "Rogue Increased damage while wielding a dagger", group: "prefix", slots: ["helmet", "body"], class: "rogue" },
  { id: "rogue-increased-damage-while-wielding-a-sword", name: "Rogue Increased damage while wielding a sword", group: "prefix", slots: ["helmet", "body"], class: "rogue" },
  { id: "rogue-increased-dancing-strikes-area", name: "Rogue Increased Dancing Strikes Area", group: "prefix", slots: ["helmet"], class: "rogue" },
  { id: "rogue-increased-throwing-physical-damage", name: "Rogue Increased Throwing Physical Damage", group: "prefix", slots: ["helmet", "body"], class: "rogue" },
  { id: "rogue-physical-penetration-with-puncture", name: "Rogue Physical penetration with Puncture", group: "prefix", slots: ["body"], class: "rogue" },
  { id: "rogue-physical-penetration-with-shadow-daggers", name: "Rogue Physical Penetration With Shadow Daggers", group: "prefix", slots: ["helmet", "body"], class: "rogue" },
  { id: "sentinel-armor-shred-effect", name: "Sentinel Armor Shred Effect", group: "prefix", slots: ["helmet", "body"], class: "sentinel" },
  { id: "sentinel-increased-fire-damage-over-time", name: "Sentinel Increased Fire Damage Over Time", group: "prefix", slots: ["helmet", "body"], class: "sentinel" },
  { id: "sentinel-increased-void-damage-over-time", name: "Sentinel Increased Void Damage Over Time", group: "prefix", slots: ["helmet", "body"], class: "sentinel" },
  { id: "sentinel-melee-physical-damage-if-wielding-a-mace", name: "Sentinel Melee Physical Damage If Wielding A Mace", group: "prefix", slots: ["helmet", "body"], class: "sentinel" },
  { id: "sentinel-melee-physical-damage-if-wielding-a-sword", name: "Sentinel Melee Physical Damage If Wielding A Sword", group: "prefix", slots: ["helmet", "body"], class: "sentinel" },
  { id: "sentinel-necrotic-damage-taken-as-physical", name: "Sentinel Necrotic Damage Taken As Physical", group: "prefix", slots: ["helmet", "body"], class: "sentinel" },
  { id: "sentinel-physical-penetration-with-bleed", name: "Sentinel Physical Penetration With Bleed", group: "prefix", slots: ["helmet", "body"], class: "sentinel" },
  { id: "sentinel-poison-damage-taken-as-physical", name: "Sentinel Poison Damage Taken As Physical", group: "prefix", slots: ["helmet", "body"], class: "sentinel" },
  { id: "sentinel-reduced-channel-cost", name: "Sentinel Reduced Channel Cost", group: "prefix", slots: ["helmet"], class: "sentinel" },
  { id: "sentinel-void-damage-taken-as-physical", name: "Sentinel Void Damage Taken As Physical", group: "prefix", slots: ["helmet", "body"], class: "sentinel" },
  { id: "acolyte-shared-bleed-chance", name: "Shared Bleed Chance On Hit", group: "prefix", slots: ["helmet", "body"], class: "acolyte" },
  { id: "primalist-shared-bleed-duration", name: "Shared Bleed Duration", group: "prefix", slots: ["helmet", "body"], class: "primalist" },
  { id: "primalist-shared-cold-damage", name: "Shared Cold Damage", group: "prefix", slots: ["helmet", "body"], class: "primalist" },
  { id: "acolyte-shared-increased-bleed-duration", name: "Shared Increased Bleed Duration", group: "prefix", slots: ["helmet", "body"], class: "acolyte" },
  { id: "acolyte-shared-increased-fire-damage", name: "Shared Increased Fire Damage", group: "prefix", slots: ["helmet", "body"], class: "acolyte" },
  { id: "primalist-shared-increased-melee-damage", name: "Shared Increased Melee Damage", group: "prefix", slots: ["helmet", "body"], class: "primalist" },
  { id: "acolyte-shared-increased-necrotic-damage", name: "Shared Increased Necrotic Damage", group: "prefix", slots: ["helmet", "body"], class: "acolyte" },
  { id: "primalist-shared-increased-spell-damage", name: "Shared Increased Spell Damage", group: "prefix", slots: ["helmet", "body"], class: "primalist" },
  { id: "primalist-shared-lightning-damage", name: "Shared Lightning Damage", group: "prefix", slots: ["helmet", "body"], class: "primalist" },
  { id: "acolyte-shared-physical-leech", name: "Shared Physical Damage Leeched As Health", group: "prefix", slots: ["helmet", "body"], class: "acolyte" },
  { id: "acolyte-shared-physical-penetration-with-bleed", name: "Shared Physical Penetration With Bleed", group: "prefix", slots: ["helmet", "body"], class: "acolyte" },
  { id: "sentinel-shield-throw-converted-to-void", name: "Shield Throw converted to Void", group: "prefix", slots: ["body"], class: "sentinel" },
  { id: "spell-damage-and-reduced-mana-cost", name: "Spell Damage and Reduced Mana Cost", group: "prefix", slots: ["one-hand"] },
  { id: "acolyte-added-spell-damage-for-curses", name: "Spell Damage for Curses", group: "prefix", slots: ["helmet"], class: "acolyte" },
  { id: "added-spell-damage-for-swords", name: "Spell Damage For Swords", group: "prefix", slots: ["one-hand"] },
  { id: "mage-spell-damage-leeched-while-channelling", name: "Spell Damage Leeched as Health while Channelling", group: "prefix", slots: ["helmet", "body"], class: "mage" },
  { id: "mage-added-spell-damage-while-channelling", name: "Spell Damage while Channelling", group: "prefix", slots: ["helmet", "body"], class: "mage" },
  { id: "strength", name: "Strength", group: "prefix", slots: ["helmet", "body", "gloves", "boots", "ring", "relic"] },
  { id: "added-stun-avoidance", name: "Stun Avoidance", group: "suffix", slots: ["ring"] },
  { id: "thorns", name: "Thorns", group: "prefix", slots: ["body", "shield"] },
  { id: "sentinel-increased-throwing-attack-crit-chance", name: "Throwing Attack Critical Strike Chance", group: "prefix", slots: ["helmet", "body"], class: "sentinel" },
  { id: "added-throwing-damage", name: "Throwing Damage", group: "prefix", slots: ["gloves", "belt", "amulet", "relic"] },
  { id: "throwing-damage-and-reduced-mana-cost", name: "Throwing Damage and Reduced Mana Cost", group: "prefix", slots: ["ring"] },
  { id: "primalist-increased-totem-crit-chance", name: "Totem Critical Strike Chance", group: "prefix", slots: ["helmet", "body"], class: "primalist" },
  { id: "primalist-increased-totem-damage", name: "Totem Damage", group: "prefix", slots: ["helmet", "body"], class: "primalist" },
  { id: "vitality", name: "Vitality", group: "prefix", slots: ["helmet", "body", "boots"] },
  { id: "void-penetration", name: "Void Penetration", group: "prefix", slots: ["amulet"] },
  { id: "void-penetration-and-minion-void-penetration", name: "Void Penetration and Minion Void Penetration", group: "suffix", slots: ["one-hand", "two-hand", "bow"] },
  { id: "void-res", name: "Void Resistance", group: "suffix", slots: ["helmet", "body", "gloves", "boots", "belt", "ring", "amulet", "relic", "catalyst", "shield", "quiver"] },
  { id: "acolyte-volatile-zombie-speed-and-damage", name: "Volatile Zombie Speed and Damage", group: "prefix", slots: ["body"], class: "acolyte" },
  { id: "ward-and-ailment-cleansing-on-potion-use", name: "Ward and Ailment Cleansing on Potion Use", group: "prefix", slots: ["belt"] },
  { id: "ward-gained-on-kill", name: "Ward Gained on Kill", group: "prefix", slots: ["amulet"] },
  { id: "rogue-ward-gained-on-use-with-shift", name: "Ward gained on use with Shift", group: "prefix", slots: ["helmet", "body"], class: "rogue" },
  { id: "rogue-ward-gained-on-use-with-smoke-bomb", name: "Ward gained on use with Smoke Bomb", group: "prefix", slots: ["helmet", "body"], class: "rogue" },
  { id: "mage-ward-per-rune-consumed-with-runic-invocation", name: "Ward Gained per Rune consumed with Runic Invocation", group: "prefix", slots: ["helmet", "body"], class: "mage" },
  { id: "rogue-ward-gained-when-you-create-a-shadow", name: "Ward Gained When You Create a Shadow", group: "prefix", slots: ["helmet", "body"], class: "rogue" },
  { id: "ward-on-potion-use", name: "Ward On Potion Use", group: "prefix", slots: ["gloves", "belt", "amulet"] },
  { id: "ward-per-second", name: "Ward Per Second", group: "suffix", slots: ["helmet", "body", "catalyst"] },
  { id: "ward-per-second-and-ward-decay-threshold", name: "Ward Per Second and Ward Decay Threshold", group: "suffix", slots: ["ring", "amulet"] },
];
