import type { AffixDef } from "./types";

/** Set shards from shattering a set item. Each one keeps that piece's item type and class. */
export const SET_AFFIXES: AffixDef[] = [
  { id: "set-apiarists-suit", name: "Apiarist's Suit", group: "set", slots: ["body"], itemType: "Body Armor", setName: "Apiarist's Set" },
  { id: "set-apiarists-smoker", name: "Apiarist's Smoker", group: "set", slots: ["catalyst"], itemType: "Off-Hand Catalyst", setName: "Apiarist's Set" },
  { id: "set-apiarists-comb", name: "Apiarist's Comb", group: "set", slots: ["one-hand"], itemType: "One-Handed Mace", setName: "Apiarist's Set" },
  { id: "set-the-last-bears-lament", name: "The Last Bear's Lament", group: "set", slots: ["helmet"], itemType: "Helmet", setName: "Last Bear's Set" },
  { id: "set-the-last-bears-fury", name: "The Last Bear's Fury", group: "set", slots: ["gloves"], itemType: "Gloves", setName: "Last Bear's Set" },
  { id: "set-the-last-bears-scorn", name: "The Last Bear's Scorn", group: "set", slots: ["body"], itemType: "Body Armor", setName: "Last Bear's Set" },
  { id: "set-isadoras-tomb-binding", name: "Isadora's Tomb Binding", group: "set", slots: ["belt"], itemType: "Belt", setName: "Isadora's Set" },
  { id: "set-isadoras-gravechill", name: "Isadora's Gravechill", group: "set", slots: ["gloves"], itemType: "Gloves", setName: "Isadora's Set" },
  { id: "set-isadoras-revenge", name: "Isadora's Revenge", group: "set", slots: ["helmet"], itemType: "Helmet", setName: "Isadora's Set" },
  { id: "set-doppelgangers-facade", name: "Doppelganger's Facade", group: "set", slots: ["helmet"], itemType: "Helmet", setName: "Doppelganger's Set", class: "rogue" },
  { id: "set-doppelgangers-deception", name: "Doppelganger's Deception", group: "set", slots: ["body"], itemType: "Body Armor", setName: "Doppelganger's Set", class: "rogue" },
  { id: "set-doppelgangers-mimicry", name: "Doppelganger's Mimicry", group: "set", slots: ["relic"], itemType: "Relic", setName: "Doppelganger's Set", class: "rogue" },
  { id: "set-kuzons-guise", name: "Kuzon's Guise", group: "set", slots: ["helmet"], itemType: "Helmet", setName: "Kuzon's Set", class: "rogue" },
  { id: "set-kuzons-fury", name: "Kuzon's Fury", group: "set", slots: ["one-hand"], itemType: "One-Handed Sword", setName: "Kuzon's Set" },
  { id: "set-corsairs-blood-cowl", name: "Corsair's Blood Cowl", group: "set", slots: ["helmet"], itemType: "Helmet", setName: "Corsair's Set", class: "rogue" },
  { id: "set-corsairs-boarding-shield", name: "Corsair's Boarding Shield", group: "set", slots: ["shield"], itemType: "Shield", setName: "Corsair's Set" },
  { id: "set-boardmans-legacy", name: "Boardman's Legacy", group: "set", slots: ["helmet"], itemType: "Helmet", setName: "Boardman's Set", class: "primalist" },
  { id: "set-boardmans-plank", name: "Boardman's Plank", group: "set", slots: ["one-hand"], itemType: "Sceptre", setName: "Boardman's Set" },
  { id: "set-boardmans-fallacy", name: "Boardman's Fallacy", group: "set", slots: ["body"], itemType: "Body Armor", setName: "Boardman's Set", class: "primalist" },
  { id: "set-sunforged-greathelm", name: "Sunforged Greathelm", group: "set", slots: ["helmet"], itemType: "Helmet", setName: "Sunforged Set", class: "sentinel" },
  { id: "set-sunforged-cuirass", name: "Sunforged Cuirass", group: "set", slots: ["body"], itemType: "Body Armor", setName: "Sunforged Set", class: "sentinel" },
  { id: "set-sunforged-hammer", name: "Sunforged Hammer", group: "set", slots: ["two-hand"], itemType: "Two-Handed Mace", setName: "Sunforged Set" },
  { id: "set-gaspars-insight", name: "Gaspar's Insight", group: "set", slots: ["helmet"], itemType: "Helmet", setName: "Gaspar's Set" },
  { id: "set-gaspars-acuity", name: "Gaspar's Acuity", group: "set", slots: ["body"], itemType: "Body Armor", setName: "Gaspar's Set" },
  { id: "set-gaspars-will", name: "Gaspar's Will", group: "set", slots: ["one-hand"], itemType: "Sceptre", setName: "Gaspar's Set" },
  { id: "set-vilatrias-storm-crown", name: "Vilatria's Storm Crown", group: "set", slots: ["helmet"], itemType: "Helmet", setName: "Vilatria's Set", class: "mage" },
  { id: "set-vilatrias-downfall", name: "Vilatria's Downfall", group: "set", slots: ["two-hand"], itemType: "Two-Handed Staff", setName: "Vilatria's Set" },
  { id: "set-halvars-stand", name: "Halvar's Stand", group: "set", slots: ["boots"], itemType: "Boots", setName: "Halvar's Set" },
  { id: "set-halvars-pledge", name: "Halvar's Pledge", group: "set", slots: ["two-hand"], itemType: "Two-Handed Staff", setName: "Halvar's Set" },
  { id: "set-last-gift-of-the-mountain", name: "Last Gift of the Mountain", group: "set", slots: ["relic"], itemType: "Relic", setName: "Halvar's Set" },
  { id: "set-jormuns-hunger", name: "Jormun's Hunger", group: "set", slots: ["one-hand"], itemType: "One-Handed Axe", setName: "Jormun's Set" },
  { id: "set-jormuns-feast", name: "Jormun's Feast", group: "set", slots: ["one-hand"], itemType: "One-Handed Sword", setName: "Jormun's Set" },
  { id: "set-jormuns-thirst", name: "Jormun's Thirst", group: "set", slots: ["belt"], itemType: "Belt", setName: "Jormun's Set" },
  { id: "set-keplahans-cryolith", name: "Keplahan's Cryolith", group: "set", slots: ["ring"], itemType: "Ring", setName: "Keplahan's Set" },
  { id: "set-keplahans-pyrolith", name: "Keplahan's Pyrolith", group: "set", slots: ["ring"], itemType: "Ring", setName: "Keplahan's Set" },
  { id: "set-locket-of-the-forgotten-knight", name: "Locket of the Forgotten Knight", group: "set", slots: ["amulet"], itemType: "Amulet", setName: "Forgotten Knight Set" },
  { id: "set-blade-of-the-forgotten-knight", name: "Blade of the Forgotten Knight", group: "set", slots: ["one-hand"], itemType: "One-Handed Sword", setName: "Forgotten Knight Set" },
  { id: "set-defiance-of-the-forgotten-knight", name: "Defiance of the Forgotten Knight", group: "set", slots: ["shield"], itemType: "Shield", setName: "Forgotten Knight Set" },
  { id: "set-the-invokers-frozen-heart", name: "The Invoker's Frozen Heart", group: "set", slots: ["amulet"], itemType: "Amulet", setName: "Invoker's Set" },
  { id: "set-the-invokers-scorching-grasp", name: "The Invoker's Scorching Grasp", group: "set", slots: ["ring"], itemType: "Ring", setName: "Invoker's Set" },
  { id: "set-the-invokers-static-touch", name: "The Invoker's Static Touch", group: "set", slots: ["ring"], itemType: "Ring", setName: "Invoker's Set" },
  { id: "set-abandoned-chitin-of-the-weaver", name: "Abandoned Chitin of the Weaver", group: "set", slots: ["ring"], itemType: "Ring", setName: "Weaver Set" },
  { id: "set-abandoned-eyes-of-the-weaver", name: "Abandoned Eyes of the Weaver", group: "set", slots: ["amulet"], itemType: "Amulet", setName: "Weaver Set" },
  { id: "set-ferebors-chisel", name: "Ferebor's Chisel", group: "set", slots: ["one-hand"], itemType: "Dagger", setName: "Ferebor's Set" },
  { id: "set-ferebors-persistence", name: "Ferebor's Persistence", group: "set", slots: ["ring"], itemType: "Ring", setName: "Ferebor's Set" },
  { id: "set-fragments-of-the-shattered-lance", name: "Fragments of the Shattered Lance", group: "set", slots: ["relic"], itemType: "Relic", setName: "Shattered Lance Set" },
  { id: "set-shard-of-the-shattered-lance", name: "Shard of the Shattered Lance", group: "set", slots: ["one-hand"], itemType: "One-Handed Sword", setName: "Shattered Lance Set" },
  { id: "set-lichs-envy", name: "Lich's Envy", group: "set", slots: ["gloves"], itemType: "Gloves", setName: "Lich's Set" },
  { id: "set-lichs-scorn", name: "Lich's Scorn", group: "set", slots: ["catalyst"], itemType: "Off-Hand Catalyst", setName: "Lich's Set" },
  { id: "set-pebbles-bitemarked-sash", name: "Pebbles' Bitemarked Sash", group: "set", slots: ["belt"], itemType: "Belt", setName: "Pebbles' Set" },
  { id: "set-pebbles-femur", name: "Pebbles' Femur", group: "set", slots: ["one-hand"], itemType: "Wand", setName: "Pebbles' Set" },
  { id: "set-pebbles-collar", name: "Pebbles' Collar", group: "set", slots: ["relic"], itemType: "Relic", setName: "Pebbles' Set" },
  { id: "set-ruby-fang-cleaver", name: "Ruby Fang Cleaver", group: "set", slots: ["one-hand"], itemType: "One-Handed Axe", setName: "Ruby Fang Set" },
  { id: "set-ruby-fang-aegis", name: "Ruby Fang Aegis", group: "set", slots: ["shield"], itemType: "Shield", setName: "Ruby Fang Set" },
  { id: "set-sinathias-dying-breath", name: "Sinathia's Dying Breath", group: "set", slots: ["one-hand"], itemType: "One-Handed Mace", setName: "Sinathia's Set" },
  { id: "set-sinathias-resurrection", name: "Sinathia's Resurrection", group: "set", slots: ["shield"], itemType: "Shield", setName: "Sinathia's Set" },
  { id: "set-zerricks-greed", name: "Zerrick's Greed", group: "set", slots: ["gloves"], itemType: "Gloves", setName: "Zerrick's Set" },
  { id: "set-zerricks-guile", name: "Zerrick's Guile", group: "set", slots: ["belt"], itemType: "Belt", setName: "Zerrick's Set" },
  { id: "set-zerricks-ambition", name: "Zerrick's Ambition", group: "set", slots: ["boots"], itemType: "Boots", setName: "Zerrick's Set" },
];
